"""new6

Revision ID: 8dae75a640fc
Revises: 810a5d5eb0ef
Create Date: 2025-04-05 21:06:34.041231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dae75a640fc'
down_revision: Union[str, None] = '810a5d5eb0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('crated_at', sa.DateTime(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('title', sa.String(length=100), nullable=False))
    op.add_column('games', sa.Column('description', sa.String(length=3000), nullable=False))
    op.add_column('games', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('games', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('games', sa.Column('end_time', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'games', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'games', 'topics', ['topic_id'], ['id'])
    op.create_foreign_key(None, 'participations', 'games', ['game_id'], ['id'])
    op.create_foreign_key(None, 'participations', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthdate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.drop_constraint(None, 'participations', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'end_time')
    op.drop_column('games', 'start_time')
    op.drop_column('games', 'score')
    op.drop_column('games', 'topic_id')
    op.drop_column('games', 'description')
    op.drop_column('games', 'title')
    op.drop_column('games', 'owner_id')
    op.drop_table('submissions')
    op.drop_table('options')
    op.drop_table('game_questions')
    op.drop_table('questions')
    op.drop_table('topics')
    # ### end Alembic commands ###
