"""new

Revision ID: ff67e39baddc
Revises: e317a26facbe
Create Date: 2025-04-04 17:30:14.299390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff67e39baddc'
down_revision: Union[str, None] = 'e317a26facbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.drop_column('users', 'firist_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firist_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
